export const ACTION_CONSTS = {
    GETTING_CAFE_OPTIONS: "GETTING_CAFE_OPTIONS",
    GETTING_CITY_OPTIONS: "GETTING_CITY_OPTIONS",
    CAFE_OPTIONS_RETURNED: "CAFE_OPTIONS_RETURNED",
    CITY_OPTIONS_RETURNED: "CITY_OPTIONS_RETURNED",
    CAFE_OPTION_LOCKED: "CAFE_OPTION_LOCKED",
    CITY_OPTION_LOCKED: "CITY_OPTION_LOCKED",
    CAFE_OPTION_UNLOCKED: "CAFE_OPTION_UNLOCKED",
    CITY_OPTION_UNLOCKED: "CITY_OPTION_UNLOCKED",
    CLEAR_CAFE_MESSAGES: "CLEAR_CAFE_MESSAGES",
    CLEAR_CITY_MESSAGES: "CLEAR_CITY_MESSAGES",
    SET_TARGET_CAFE: "SET_TARGET_CAFE",
    SET_TARGET_CITY: "SET_TARGET_CITY",
    GET_AVAILABLE_CITIES: "GET_AVAILABLE_CITIES",
    FIND_MOST_SIMILAR: "FIND_MOST_SIMILAR",
    CLEAR_SEARCH: "CLEAR_SEARCH",
    PERMISSION_UPDATED: "PERMISSION_UPDATED",
    TAB_SWITCHED: "TAB_SWITCHED"
}

export default ACTION_CONSTS;