export const ACTION_CONSTS = {
    GETTING_CAFE_OPTIONS: "GETTING_CAFE_OPTIONS",
    GETTING_CITY_OPTIONS: "GETTING_CITY_OPTIONS",
    CAFE_OPTIONS_RETURNED: "CAFE_OPTIONS_RETURNED",
    CITY_OPTIONS_RETURNED: "CITY_OPTIONS_RETURNED",
    SET_TARGET_CAFE: "SET_TARGET_CAFE",
    SET_TARGET_CITY: "SET_TARGET_CITY",
    GET_AVAILABLE_CITIES: "GET_AVAILABLE_CITIES",
    PERMISSION_UPDATED: "PERMISSION_UPDATED",
    TAB_SWITCHED: "TAB_SWITCHED"
}

export default ACTION_CONSTS;