# Generated by Django 3.0.5 on 2020-04-07 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('place_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='PlaceId')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price_level', models.PositiveSmallIntegerField(verbose_name='PriceLevel')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Rating')),
                ('user_ratings_total', models.IntegerField(verbose_name='UserRatingsTotal')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Placetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ReviewId')),
                ('reviewer', models.CharField(max_length=255, verbose_name='Name')),
                ('datetime', models.CharField(max_length=30, verbose_name='DateTime')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Rating')),
                ('text', models.TextField(verbose_name='Text')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Cafes_Placetypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Cafe')),
                ('placetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Placetype')),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.City'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='placetypes',
            field=models.ManyToManyField(related_name='type', through='webapp.Cafes_Placetypes', to='webapp.Placetype'),
        ),
    ]
