# Generated by Django 3.0.5 on 2020-04-14 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('place_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='PlaceId')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price_level', models.PositiveSmallIntegerField(null=True, verbose_name='PriceLevel')),
                ('hours', models.CharField(default='unset', max_length=255, null=True, verbose_name='Hours')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Rating')),
                ('user_ratings_total', models.IntegerField(null=True, verbose_name='UserRatingsTotal')),
                ('address', models.CharField(default='unset', max_length=255, verbose_name='Addr')),
                ('compound_code', models.CharField(max_length=255, null=True, verbose_name='CompoundCode')),
                ('website', models.CharField(max_length=255, null=True, verbose_name='Website')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCode', models.CharField(default='Unset', max_length=255, verbose_name='CountryCode')),
            ],
        ),
        migrations.CreateModel(
            name='Placetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ReviewId')),
                ('reviewer', models.CharField(max_length=255, verbose_name='Name')),
                ('datetime', models.CharField(max_length=30, verbose_name='DateTime')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Rating')),
                ('text', models.TextField(verbose_name='Text')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Country')),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.City'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='placetypes',
            field=models.ManyToManyField(null=True, to='webapp.Placetype'),
        ),
    ]
