# Generated by Django 3.0.5 on 2020-04-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200417_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='address',
            field=models.CharField(blank=True, default='unset', max_length=255, null=True, verbose_name='Addr'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='hours',
            field=models.CharField(blank=True, default='unset', max_length=255, null=True, verbose_name='Hours'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='price_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PriceLevel'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='user_ratings_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='UserRatingsTotal'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
    ]
