# Generated by Django 3.0.5 on 2020-05-05 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200417_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_ref', models.CharField(max_length=255, verbose_name='ReferenceID')),
                ('html_attr', models.CharField(blank=True, max_length=255, verbose_name='PhotographerLink')),
                ('height', models.PositiveSmallIntegerField(blank=True, verbose_name='Height')),
                ('width', models.PositiveSmallIntegerField(blank=True, verbose_name='Width')),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Cafe')),
            ],
        ),
    ]
