# Generated by Django 3.0.5 on 2020-05-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200504_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='placetypes',
            field=models.ManyToManyField(null=True, to='webapp.Placetype'),
        ),
    ]
