# Generated by Django 3.0.5 on 2020-05-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20200504_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='formatted_phone_number',
            field=models.CharField(max_length=255, null=True, verbose_name='FormattedPhoneNumber'),
        ),
    ]
