# Generated by Django 3.0.5 on 2020-05-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_cafe_formatted_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='address',
            new_name='formatted_address',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='placetypes',
            field=models.ManyToManyField(to='webapp.Placetype'),
        ),
    ]
