# Generated by Django 3.0.5 on 2020-05-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20200511_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='lng',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True, verbose_name='Longitude'),
        ),
    ]
