# Generated by Django 3.0.5 on 2020-05-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20200513_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='lng',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True, verbose_name='Longitude'),
        ),
    ]
