# Generated by Django 3.0.5 on 2020-06-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20200527_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo_src',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PhotoSrc'),
        ),
    ]
