# Generated by Django 3.0.5 on 2020-07-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20200604_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='photo_src',
            field=models.CharField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/c/c4/OldhamTownCentre.jpg', max_length=255, verbose_name='PhotoSrc'),
        ),
    ]
