# Generated by Django 3.0.5 on 2020-07-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20200719_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='radius',
            field=models.IntegerField(blank=True, default=2500, verbose_name='Radius'),
        ),
    ]
