# Generated by Django 3.0.5 on 2020-07-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20200721_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='city',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='city',
            name='lng',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude'),
        ),
    ]
